version: "3"

services:
  app:
    image: yuemanwai/wikipedia
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      SECRET_KEY: you-will-never-guess
      DATABASE_URL: postgresql://postgres:postgres@postgresdb:5432/postgres
    networks:
      - flask_app
    ports:
      - 5000:5000
      
  postgresdb:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - flask_app
    restart: unless-stopped

networks:
  flask_app:
    driver: bridge

volumes:
  postgres:
