"""empty message

Revision ID: 163ae34ec2d3
Revises: 3dee56f6577b
Create Date: 2024-04-02 13:37:35.853715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163ae34ec2d3'
down_revision = '3dee56f6577b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('watchlist_follower_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('watchlist_followed_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('follower_id')
        batch_op.drop_column('followed_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followed_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('watchlist_followed_post_id_fkey', 'post', ['followed_post_id'], ['id'])
        batch_op.create_foreign_key('watchlist_follower_id_fkey', 'user', ['follower_id'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
