"""empty message

Revision ID: 35f65d472071
Revises: 9b428eade5fb
Create Date: 2024-04-02 12:22:59.518598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f65d472071'
down_revision = '9b428eade5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('article_content', sa.String(length=2000), nullable=True))
        batch_op.drop_index('ix_post_title')
        batch_op.create_index(batch_op.f('ix_post_article_title'), ['article_title'], unique=True)
        batch_op.drop_column('title')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_article_title'))
        batch_op.create_index('ix_post_title', ['title'], unique=False)
        batch_op.drop_column('article_content')
        batch_op.drop_column('article_title')

    # ### end Alembic commands ###
