"""empty message

Revision ID: 3dee56f6577b
Revises: 35f65d472071
Create Date: 2024-04-02 12:54:29.205990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dee56f6577b'
down_revision = '35f65d472071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('body', sa.String(length=2000), nullable=True))
        batch_op.drop_index('ix_post_article_title')
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=True)
        batch_op.drop_column('article_title')
        batch_op.drop_column('article_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_content', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('article_title', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.create_index('ix_post_article_title', ['article_title'], unique=False)
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
