"""empty message

Revision ID: dc3c5102664b
Revises: 
Create Date: 2024-04-23 15:02:44.280030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3c5102664b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_event', schema=None) as batch_op:
        batch_op.drop_constraint('current_event_message_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_event', schema=None) as batch_op:
        batch_op.create_unique_constraint('current_event_message_key', ['message'])

    # ### end Alembic commands ###
