"""empty message

Revision ID: f19d86a12632
Revises: 
Create Date: 2024-03-29 09:40:05.125087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f19d86a12632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_table('followers')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edit_time', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_post_timestamp')
        batch_op.create_index(batch_op.f('ix_post_create_time'), ['create_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_edit_time'), ['edit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=True)
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.drop_index(batch_op.f('ix_post_edit_time'))
        batch_op.drop_index(batch_op.f('ix_post_create_time'))
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('edit_time')
        batch_op.drop_column('create_time')
        batch_op.drop_column('title')

    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey')
    )
    op.drop_table('watchlist')
    # ### end Alembic commands ###
